---
- hosts: www
  vars:
    - root_dir: "{{playbook_dir}}"

  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:

    - {
        role: "sa-nginx"
      }
    - {
        role: "sa-include",
        include_file: "{{root_dir}}/demosite.yml"
      }
    - {
        role: "sa-lets-encrypt",
        le_ca: https://acme-staging.api.letsencrypt.org/directory,
        option_run_once: true,
        option_setup_cron: true
      }


  tasks:
    - debug: msg="Tasks section"
